### ISSUE TITLE
Sometimes Incorrect state while loading messages

### ISSUE THREAD

**Issue by JenyaKirmizaTripTop** [Pushwoosh/pushwoosh-inbox-ui-android-sdk#2] opened 2019-05-09 08:28 UTC
```
Fatal Exception: java.lang.IllegalArgumentException: Incorrect state.
       at com.pushwoosh.inbox.internal.b.a(b.java:36)
       at com.pushwoosh.inbox.PushwooshInbox.loadMessages(PushwooshInbox.java)
       at com.wenor.uia.checking.fragment.inboxNotification.model.repository.InboxRepository.loadInbox(InboxRepository.java:87)
       at com.wenor.uia.checking.fragment.inboxNotification.presentation.presenter.InboxPresenter.onCreate(InboxPresenter.java:71)
       at com.wenor.uia.checking.fragment.inboxNotification.presentation.view.fragment.BaseFragment.onCreate(BaseFragment.java:48)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2528)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:843)
       at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1196)
       at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1079)
       at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:118)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1858)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1816)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1723)
       at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:146)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Hi, can someone help to fix this issue? i don't understand why it's happening

**Comment by wfhm** [comment] 2019-05-16 11:30
Hello @JenyaKirmizaTripTop ,

May I ask you to provide a bit more details on the issue? Which Pushwoosh SDK version do you use? When exactly does this exception occur?

**Comment by JenyaKirmizaTripTop** [comment] 2019-05-23 11:16
```
    implementation 'com.pushwoosh:pushwoosh:5.9.3'
    implementation "com.pushwoosh:pushwoosh-inbox:5.9.3"
    implementation "com.pushwoosh:pushwoosh-inbox-ui:5.9.3"
```

It happens when i'm loading inbox messages. I don't know the exact scenario, cause it happens randomly.

**Comment by wfhm** [comment] 2019-06-27 11:47
@JenyaKirmizaTripTop apologies for a delayed response. The issue is fixed with the latest release.

**Closed as completed by wfhm** 2019-06-27 11:47 UTC
